apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: flux-system
        namespace: flux-system
      data:
        identity: identity
        "identity.pub": identity_pub
    target:
      kind: Secret
      name: flux-system
      namespace: flux-system