apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      metadata:
        name: all
      spec:
        secretRef:
          name: flux-sync
    target:
      kind: GitRepository
      labelSelector: kustomize.toolkit.fluxcd.io/name=flux-system