apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Secret
      metadata:
        name: flux-system
        namespace: flux-system
      data:
        identity: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWtXChlTSBaTm6xWBuia5T+HpcN96GlNnm7Rn0L4CRVo1RmPzgkctd0rSR1hecrke2isSMTKMB8G31JG5BdJV5WkQ/HIIkgDiL8sdZ4fe8IS32JSX6gj1wN9Y4VRvaimb8SGSNAf85I5SxkHTegYj7XHFTvcFqSoRHrFHHLhpaKjUnYhfVSEcEo2Qk1gBtz7GN9AsDDXNfX1jTxeiEWgsyBM+6Ky6t3aKPG8Q49aHKvCWa26El5OFo8bCUBHJixp2AObI1zezxdNsr6s1lLflv55j6lVWmFHwXAsQ5p1rhXRhs1TNlpE4vdwWwVyiLTcscsuWJe+5Hkqo7FFT5xYZl3Kih/9UW1ct8UMbPaAtMWeBiZmG3cFzQ2wq8v9xogXamaCrg0eWe0jZSS1sNYbrCuC1KSPc+lHMIPTHpCf0OD02H9P/yGfwL26NFB02wTZtGwXX1E1CwFVOtQlLFGJU/EgwnG1aQxc1pC4vmVLXqf+pNHH2eunAhDiOFECPgGCE= wsl@BY006

        "identity.pub": ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHbC4s6jrbQs92cC2SGfup/p1YLWM5DciXp0SpsrxLZIVM32JS/+fUtK+/8PpLQZInONgNwPSWmeqQuIZl0GaXia/RSGE9foEIaRtHAD+xO7mcILUeX0VybfQIuY3ZdZoEVuI5j4pY9+fF/6dC0/cI9GhT0aMGwbFFUBer9+JUNTqMhRVE5lJSRxYhh9ExhtIOgWNWU4sn5jte+Fj1Gv63JgCLGCNqxLgntNsuHkQgG5lqTORj1j8+9u59oCtDNDnj97pv3iV2mLhPnHWq6wto4NlvVDONmaLth16tzAOndbyH7AqafLEgwiY5WGCJHhN9u4Qal/nN3HPflMg6qoW4hwq3avJCzVHEXVIOBDYi/VyhbdH72qn/0W7KIqzyaBEyPlzL21r6PU2YNL7V3Gtlo4ZO+7REEbl2eKuNC2ir1rWXYIkzL/YbsogtrxnfWDdsMf0yYBv8FgAMs/wurcvx+1t4E0fJihjXsW43ppgJMkHKycoti43+wUrQdYfMLuE= craig.hurt@blakyaks.com

    target:
      kind: Secret
      name: flux-system
      namespace: flux-system